/**
 * Synthetic demo lectures (Teaching Conference items).
 *
 * Each `audioScript` is an array of sections. The audio player reads one
 * section at a time so the learner can pause, rewind a section, or let it
 * advance automatically. Aim for three to seven minutes total.
 *
 * All content here is original synthetic teaching material written for this
 * demo. Nothing is copied from any published source.
 */

import type { LectureInput } from "@/content/schema";

export const DEMO_LECTURES: LectureInput[] = [
  {
    code: "DEMO-LEC-001",
    title: "Approach to Chest Pain",
    specialty: "Internal Medicine",
    topic: "Cardiology",
    lectureType: "MORNING_REPORT",
    summary:
      "A structured way to work through undifferentiated chest pain, prioritizing the diagnoses that kill quickly.",
    audioScript: [
      "Good morning. Chest pain is the complaint where a structured approach matters most, because the differential ranges from musculoskeletal strain to conditions that will kill the patient within the hour. The organizing principle is simple: before you reason toward what is likely, actively exclude what is lethal.",
      "There are a handful of diagnoses you exclude first. Acute coronary syndrome. Pulmonary embolism. Aortic dissection. Tension pneumothorax. Esophageal rupture. Pericardial tamponade. Each of these has a characteristic story, and each has a first test that either raises or lowers your suspicion substantially.",
      "Your initial data set is deliberately small and fast. Vital signs in both arms if dissection is a consideration. An electrocardiogram within ten minutes of arrival. A focused examination looking at jugular venous pressure, breath sounds, and pulses. That combination will point you toward the right branch in most patients.",
      "The electrocardiogram is the highest-yield early test. ST elevation moves the patient toward emergent reperfusion. ST depression with ischemic symptoms suggests non-ST elevation acute coronary syndrome, which means aggressive medical therapy and risk stratification. Diffuse ST elevation with PR depression suggests pericarditis. A normal tracing does not exclude ischemia, and that is worth repeating: serial tracings matter when the story is convincing.",
      "Pretest probability should drive your testing, not the other way around. In a patient with recent surgery and sudden pleuritic pain, a D-dimer will be elevated and will not help you; go directly to computed tomography pulmonary angiography. In a low-risk young patient with atypical features, a negative D-dimer can end the workup. The test you choose is a consequence of the probability you have already estimated.",
      "Finally, disposition. Chest pain that has been fully characterized as low risk with negative biomarkers and a reassuring tracing can often be managed as an outpatient with follow-up. Anything with elevated troponin, dynamic changes, or hemodynamic abnormality is an admission. When you are uncertain, the safe default is observation with serial evaluation rather than discharge with a plan to see how it goes.",
    ],
    keyPoints: [
      "Exclude the lethal causes before reasoning toward the likely ones.",
      "An electrocardiogram within ten minutes is the highest-yield early test.",
      "Estimate pretest probability first; it determines which test is useful.",
      "A single normal ECG does not exclude ischemia — repeat it when the story is convincing.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["CARD.CP.01", "CARD.ACS.01", "CARD.ACS.02", "EM.PE.01"],
  },
  {
    code: "DEMO-LEC-002",
    title: "Acute Coronary Syndrome",
    specialty: "Internal Medicine",
    topic: "Cardiology",
    lectureType: "CORE_LECTURE",
    summary:
      "How the electrocardiogram splits acute coronary syndrome into two management pathways, and what therapy each one requires.",
    audioScript: [
      "Acute coronary syndrome is best understood as one disease with two management pathways, and the electrocardiogram is what sorts patients between them. That single decision drives everything that follows.",
      "Pathway one is ST-elevation myocardial infarction. There is a fully occluded epicardial vessel and myocardium is dying now. The management is emergent reperfusion, preferably by primary percutaneous intervention, with fibrinolysis as the alternative when timely catheterization is not available. Time is the only variable that matters.",
      "Pathway two is non-ST elevation acute coronary syndrome, which includes non-ST elevation myocardial infarction and unstable angina. Here the vessel is not completely occluded. The management is aggressive medical therapy immediately, plus an invasive evaluation whose urgency is determined by risk. Critically, the medical therapy does not wait for the catheterization.",
      "That medical therapy is a bundle you should be able to recite. Aspirin, given immediately unless truly contraindicated. Therapeutic anticoagulation. A high-intensity statin. A beta blocker once the patient is not in cardiogenic shock. Nitrates and oxygen for symptoms and hypoxemia, remembering that neither changes mortality.",
      "Biomarkers tell you about myocardial injury but they do not make the reperfusion decision. Serial troponins define whether infarction occurred and contribute to risk stratification. A rising pattern with ischemic symptoms and dynamic electrocardiographic changes places the patient in a group that benefits from an invasive strategy during the admission.",
      "Secondary prevention starts before the patient leaves. Dual antiplatelet therapy where indicated. High-intensity statin. Beta blocker. Renin-angiotensin system inhibition when there is reduced ejection fraction, diabetes or hypertension. Cardiac rehabilitation referral. Smoking cessation. Risk factor control. This bundle is the intervention with the largest effect on what happens to the patient over the next five years, and it is the part most often left incomplete.",
    ],
    keyPoints: [
      "The ECG splits acute coronary syndrome into two distinct management pathways.",
      "ST elevation means emergent reperfusion; time is the only variable that matters.",
      "In non-ST elevation disease, medical therapy starts immediately and does not wait for catheterization.",
      "Secondary prevention is started during the admission, not deferred.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["CARD.ACS.01", "CARD.ACS.02", "CARD.ACS.03", "CARD.ACS.04", "CARD.ACS.05"],
  },
  {
    code: "DEMO-LEC-003",
    title: "Atrial Fibrillation",
    specialty: "Internal Medicine",
    topic: "Cardiology",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Recognition, the stability branch point, rate versus rhythm control, and the stroke-prevention decision that outlasts the admission.",
    audioScript: [
      "Atrial fibrillation is the most common sustained arrhythmia you will manage, and the reasoning is unusually clean once you know the sequence.",
      "Recognition first. On the electrocardiogram you are looking for an irregularly irregular rhythm with no discrete P waves. The QRS is usually narrow. If the rate is above roughly one hundred, you call it atrial fibrillation with rapid ventricular response.",
      "The next question is the one that matters most acutely: is the patient hemodynamically stable? Instability means hypotension, hypoperfusion, altered mental status, ongoing ischemic chest pain, or acute pulmonary edema. An unstable patient gets immediate synchronized cardioversion. Notice that a fast rate by itself is not instability — a patient can have a rate of one hundred fifty and be perfectly well perfused.",
      "For the stable patient, the acute goal is rate control. A beta blocker or a nondihydropyridine calcium channel blocker will usually bring the ventricular response down. Choice depends on ventricular function and comorbidities. While you do that, look for the precipitant: infection, anemia, thyrotoxicosis, alcohol, pulmonary embolism, heart failure, or the perioperative state.",
      "Rate control versus rhythm control is a longer conversation and generally not an emergency department decision. For most patients rate control with anticoagulation performs as well as pursuing sinus rhythm. Rhythm control is favored in younger patients, in those with persistent symptoms despite adequate rate control, and in some patients with heart failure.",
      "Which brings us to the part that actually changes life expectancy: stroke prevention. Atrial fibrillation increases stroke risk substantially, and the decision to anticoagulate is made using a validated clinical risk score weighed against bleeding risk. This decision is not deferred vaguely to the outpatient setting. Before the patient leaves, there should be a documented assessment and either a prescription or an explicit reason not to write one, with a named clinician who owns the follow-up.",
    ],
    keyPoints: [
      "Irregularly irregular, narrow complex, no discrete P waves.",
      "Stability, not heart rate, decides between cardioversion and rate control.",
      "Look for a precipitant — infection, thyrotoxicosis, anemia, alcohol, embolism.",
      "The anticoagulation decision must be explicit and documented before discharge.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["CARD.AF.01", "CARD.AF.02", "CARD.AF.03", "CARD.AF.04"],
  },
  {
    code: "DEMO-LEC-004",
    title: "Acute Heart Failure",
    specialty: "Internal Medicine",
    topic: "Cardiology",
    lectureType: "CORE_LECTURE",
    summary:
      "Recognizing congestion, decongesting safely, and separating symptom relief from the therapies that change mortality.",
    audioScript: [
      "Acute decompensated heart failure is, in the great majority of cases, a volume problem. Recognizing that reframes the whole admission.",
      "The diagnosis is made at the bedside. Elevated jugular venous pressure is the single most useful sign — it estimates filling pressure directly. Add an S3 gallop, bibasilar crackles, peripheral edema, orthopnea and a documented weight gain, and you have congestion. Natriuretic peptides help when the cause of dyspnea is genuinely ambiguous, and the chest radiograph shows vascular congestion and effusions.",
      "Treatment is decongestion with intravenous loop diuretics. Oral absorption is unreliable when the gut itself is congested, so the intravenous route matters. Dose relative to the patient's home dose rather than starting from scratch, and reassess early rather than waiting a full day to find out it was inadequate.",
      "You follow response with daily standing weights, strict intake and output, and serial examination of jugular venous pressure and oxygen requirement. Repeated biomarkers and daily radiographs lag behind the clinical picture and rarely change what you do.",
      "You also follow the predictable harms. Loop diuretics waste potassium and magnesium, so both need active repletion. Over-diuresis raises creatinine. Check chemistry at least daily during aggressive decongestion.",
      "Now the crucial distinction. Diuretics make patients feel dramatically better and do not extend life. The mortality benefit in reduced ejection fraction belongs to neurohormonal blockade: renin-angiotensin system inhibition, an evidence-based beta blocker, and mineralocorticoid receptor antagonism, with additional agents in current guideline regimens. The admission is your opportunity to start or optimize this regimen.",
      "Finally, ask why the patient decompensated. Medication nonadherence, dietary sodium, a missed diuretic, new arrhythmia, ischemia, infection, or a recently added medication. If you discharge without addressing the precipitant, you have scheduled the readmission.",
    ],
    keyPoints: [
      "Jugular venous pressure is the best bedside estimate of filling pressure.",
      "Intravenous loop diuretics decongest; oral absorption is unreliable in a congested gut.",
      "Follow weights, intake and output, electrolytes and renal function daily.",
      "Diuretics relieve symptoms; neurohormonal blockade extends life.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["CARD.HF.01", "CARD.HF.02", "CARD.HF.03", "CARD.HF.04"],
  },
  {
    code: "DEMO-LEC-005",
    title: "Pneumonia and Inpatient Respiratory Infection",
    specialty: "Internal Medicine",
    topic: "Pulmonology",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Three sequential decisions: does the patient have pneumonia, how sick are they, and what does that site of care require.",
    audioScript: [
      "Pneumonia looks like a single decision but it is really three decisions made in order, and keeping them separate prevents most of the errors.",
      "Decision one: is this pneumonia? You need a compatible clinical syndrome — fever, cough, dyspnea, focal examination findings — plus a radiographic infiltrate. Without the infiltrate you are usually looking at bronchitis, which does not warrant antibiotics in most patients.",
      "Decision two: how sick is this patient? This determines the site of care, and it is where severity indices earn their place. You are integrating age, comorbidity, mental status, respiratory rate, blood pressure, blood urea nitrogen and oxygenation. The output is one of three answers: outpatient, general ward, or intensive care.",
      "Decision three follows automatically. Site of care determines empiric coverage. The outpatient with no comorbidity is treated differently from the ward patient, who is treated differently from the patient in shock or requiring ventilation. For the typical non-critically ill inpatient, a beta-lactam plus a macrolide covers typical and atypical organisms.",
      "Blood cultures are reasonable in the hospitalized patient and should never delay antibiotics. Follow oxygenation closely, because the oxygen requirement is one of your discharge criteria.",
      "Speaking of which: discharge readiness is a clinical judgment, not a radiographic one. Afebrile with stable vital signs, oxygenating at the patient's baseline, tolerating oral intake and oral medication. Infiltrates take weeks to clear on film, so a repeat radiograph before discharge answers a question nobody asked.",
      "Do not leave without addressing prevention. Pneumococcal and influenza vaccination status is easy to close during an admission and easy to forget. If the patient smokes, this is the moment for cessation counseling and pharmacotherapy.",
    ],
    keyPoints: [
      "Compatible syndrome plus a radiographic infiltrate makes the diagnosis.",
      "Severity assessment determines site of care, which determines empiric coverage.",
      "Discharge readiness is clinical stability, not radiographic clearing.",
      "Close vaccination gaps and address smoking before the patient leaves.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PULM.CAP.01", "PULM.CAP.02", "PULM.CAP.03", "PULM.CAP.04", "PULM.CAP.05"],
  },
  {
    code: "DEMO-LEC-006",
    title: "COPD and Asthma Exacerbations",
    specialty: "Internal Medicine",
    topic: "Pulmonology",
    lectureType: "CORE_LECTURE",
    summary:
      "Shared acute therapy for obstructive exacerbations, the COPD-specific oxygen target, and the signs of impending respiratory failure.",
    audioScript: [
      "Asthma and chronic obstructive pulmonary disease exacerbations share most of their acute management and differ in a few specifics that matter enormously.",
      "The shared core is straightforward. Inhaled short-acting bronchodilators, given repeatedly and early. Systemic corticosteroids, given early, because they reduce treatment failure and relapse. Oxygen for hypoxemia. Assessment of the need for ventilatory support.",
      "The first important difference is the oxygen target. In chronic obstructive pulmonary disease, titrate to a saturation of roughly eighty-eight to ninety-two percent. Driving the saturation toward one hundred can worsen carbon dioxide retention through several mechanisms. In asthma there is no such concern; correct hypoxemia normally.",
      "The second difference is antibiotics. In a chronic obstructive pulmonary disease exacerbation, antibiotics are indicated when the cardinal symptoms are present: increased dyspnea, increased sputum volume and increased sputum purulence. In asthma, antibiotics have no role absent evidence of bacterial pneumonia. Wheeze is bronchospasm, not infection.",
      "Now the part to internalize: recognizing the patient who is about to fail. The reassuring patient is the one who is loudly wheezing, speaking in sentences, and moving air. The dangerous patient has a quiet chest with poor air movement, is becoming drowsy or agitated, is showing paradoxical abdominal motion, and has a carbon dioxide that is normal or rising when it should be low. A normalizing carbon dioxide in a tachypneic obstructed patient means fatigue, not improvement.",
      "For chronic obstructive pulmonary disease with respiratory acidosis or severe work of breathing, noninvasive positive pressure ventilation used early reduces the need for intubation and reduces mortality. Sedatives are dangerous here — anxiolysis in a hypercapnic patient can precipitate respiratory arrest.",
      "Before discharge, fix what caused the visit. In asthma that is usually the absence of controller therapy, poor inhaler technique or a missing spacer, and no written action plan. In chronic obstructive pulmonary disease it is maintenance therapy, technique, vaccination, and above all smoking cessation, which is the only intervention that meaningfully alters the disease trajectory.",
    ],
    keyPoints: [
      "Bronchodilators plus early systemic steroids are the shared acute core.",
      "COPD has a modest oxygen target of 88 to 92 percent; asthma does not.",
      "A quiet chest with a rising carbon dioxide is pre-arrest, not improvement.",
      "Fix the home regimen — controller therapy, technique, action plan, cessation.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["PULM.COPD.01", "PULM.COPD.02", "PULM.COPD.03", "PULM.COPD.04", "PEDS.ASTHMA.02", "PEDS.ASTHMA.03"],
  },
  {
    code: "DEMO-LEC-007",
    title: "DKA and Hyperglycemic Emergencies",
    specialty: "Internal Medicine",
    topic: "Endocrinology",
    lectureType: "CORE_LECTURE",
    summary:
      "The fluids-potassium-insulin sequence, why the anion gap rather than glucose is the endpoint, and how to transition off the infusion.",
    audioScript: [
      "Diabetic ketoacidosis has a fixed sequence, and most of the harm in this condition comes from performing the steps out of order.",
      "The diagnostic triad is hyperglycemia, an anion-gap metabolic acidosis, and ketosis. All three are needed. Hyperglycemia alone without acidosis and ketones is not ketoacidosis, and the hyperosmolar hyperglycemic state has much higher glucose with minimal ketosis and a different fluid strategy.",
      "Step one is fluid. Isotonic crystalloid restores intravascular volume and renal perfusion, and it lowers glucose meaningfully by itself through dilution and improved renal clearance. Fluid comes before insulin, always.",
      "Step two is potassium. This is the step that kills patients when skipped. Total-body potassium is profoundly depleted after days of osmotic diuresis, even though the measured serum potassium often looks normal or high — because acidosis and insulin deficiency have shifted potassium out of the cells. When you give insulin, it drives potassium back into cells and the serum level can fall precipitously. So: check the potassium, and if it is below roughly three point three, replete before starting insulin.",
      "Step three is insulin, usually as a continuous infusion. Insulin stops ketogenesis, which is the actual problem.",
      "Now the monitoring endpoint. Glucose normalizes long before ketogenesis stops. If you stop insulin when the glucose looks good, the gap reopens and the patient bounces back into ketoacidosis. The endpoint is anion gap closure. When glucose falls below roughly two hundred and the gap is still open, add dextrose to the fluids so you can keep the insulin running.",
      "The transition off the infusion has a rule that is easy to remember and easy to skip. Intravenous insulin has a half-life measured in minutes. Give the subcutaneous insulin and let it overlap with the infusion for one to two hours before stopping the drip. The patient should also be eating.",
      "Finally, find the precipitant. Infection, missed insulin, a new diagnosis, a cardiovascular event, or a medication. In practice, cost-related insulin nonadherence is common, entirely fixable, and will bring the patient straight back if you do not address it before discharge.",
    ],
    keyPoints: [
      "Fluids first, then check potassium, then start insulin.",
      "Serum potassium reports distribution, not total-body stores.",
      "The anion gap, not glucose, is the endpoint of the insulin infusion.",
      "Overlap subcutaneous insulin with the drip for one to two hours before stopping it.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["ENDO.DKA.01", "ENDO.DKA.02", "ENDO.DKA.03", "ENDO.DKA.04", "ENDO.DKA.05", "ENDO.DKA.06"],
  },
  {
    code: "DEMO-LEC-008",
    title: "Initial Approach to GI Bleeding",
    specialty: "Internal Medicine",
    topic: "Gastroenterology",
    lectureType: "MORNING_REPORT",
    summary:
      "Resuscitate before you diagnose, transfuse restrictively, and remove the medication that caused the bleed.",
    audioScript: [
      "Gastrointestinal bleeding is a resuscitation problem before it is a diagnostic one, and residents who reverse that order get into trouble.",
      "The first minutes are about access and volume. Two large-bore intravenous lines. A type and screen so crossmatched blood is available before you need it. Crystalloid, then blood products when indicated. Only then do you start asking where the bleeding is coming from.",
      "Localization is largely clinical. Melena — black, tarry, foul stool — indicates digested blood and therefore an upper source. A disproportionately elevated blood urea nitrogen relative to creatinine supports that, because the nitrogen load from digested blood is absorbed. Bright red blood per rectum is usually a lower source, though a brisk upper bleed can present that way in an unstable patient.",
      "Transfusion strategy has changed and it is worth being precise. A restrictive threshold, transfusing at a hemoglobin around seven grams per deciliter, produces better outcomes than a liberal strategy in most stable patients. Aggressive transfusion can raise portal pressures and worsen variceal bleeding. Active bleeding with hemodynamic compromise, or significant cardiac disease, shifts that threshold upward.",
      "For upper bleeding, intravenous proton pump inhibitor therapy stabilizes clot and reduces the need for endoscopic reintervention. Endoscopy is the definitive step: it identifies the source, treats it, and gives you prognostic information about rebleeding risk. Timing is generally within twenty-four hours in the resuscitated patient.",
      "Do not forget the medication history, because it usually contains the cause and the cure. Nonsteroidal anti-inflammatory drugs, antiplatelet agents and anticoagulants all increase bleeding and rebleeding risk. Stopping the offending nonsteroidal, continuing acid suppression, and testing for Helicobacter pylori is what prevents this admission from repeating in six months.",
    ],
    keyPoints: [
      "Two large-bore lines, type and screen, and volume — before diagnosis.",
      "Melena with an elevated blood urea nitrogen indicates an upper source.",
      "Use a restrictive transfusion threshold in most stable patients.",
      "Remove the causative nonsteroidal and test for Helicobacter pylori.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["GI.UGIB.01", "GI.UGIB.02", "GI.UGIB.03", "GI.UGIB.04"],
  },
  {
    code: "DEMO-LEC-009",
    title: "Sepsis and Early Resuscitation",
    specialty: "Internal Medicine",
    topic: "Infectious Disease",
    lectureType: "GRAND_ROUNDS",
    summary:
      "Recognizing sepsis, the time-critical bundle, and the reassessment step that decides what happens next.",
    audioScript: [
      "Sepsis is infection plus organ dysfunction, and the reason we drill it as a bundle is that every hour of delay measurably worsens survival.",
      "Recognition is the bottleneck. You are looking for a patient with a suspected or confirmed infection who also has evidence of organ dysfunction: hypotension, altered mental status, tachypnea, an elevated lactate, acute kidney injury, thrombocytopenia, or a rising bilirubin. The clinical impression that the patient looks worse than the individual numbers suggest is often the earliest signal.",
      "The bundle is short. Draw blood cultures and site-specific cultures before antibiotics when it can be done without delay. Measure a lactate. Give balanced crystalloid for hypotension or an elevated lactate. Give broad-spectrum antibiotics promptly, targeted at the likely source and the local resistance pattern.",
      "Then comes the step that is most often skipped: reassess. After the initial fluid resuscitation, go back to the bedside. Blood pressure, heart rate, mental status, urine output, capillary refill and peripheral perfusion, and a repeat lactate. This reassessment tells you whether the patient is fluid-responsive or whether they need vasopressors, and it is the difference between resuscitating a patient and merely ordering fluids.",
      "Source control is the part that antibiotics cannot substitute for. An obstructed infected urinary tract, an undrained abscess, an infected necrotic tissue bed, an infected device — none of these will resolve on antimicrobials alone. If a septic patient is not improving on appropriate antibiotics, the answer is almost never a broader antibiotic. It is imaging to find what needs draining.",
      "As the patient improves, de-escalate. Narrow the antibiotic once cultures return. Transition to oral therapy when the patient is afebrile, improving, and absorbing. Define the treatment duration explicitly, because indefinite broad-spectrum therapy causes its own harms.",
    ],
    keyPoints: [
      "Sepsis is infection plus organ dysfunction; recognition is the bottleneck.",
      "Cultures, lactate, fluids and prompt antibiotics — without delay.",
      "Reassess perfusion after resuscitation; that step decides vasopressor need.",
      "A patient failing appropriate antibiotics needs source control, not broader coverage.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["ID.SEPSIS.01", "ID.SEPSIS.02", "ID.SEPSIS.03", "ID.SEPSIS.04", "ID.PYELO.01"],
  },
  {
    code: "DEMO-LEC-010",
    title: "Acute Ischemic Stroke",
    specialty: "Neurology",
    topic: "Stroke",
    lectureType: "CORE_LECTURE",
    summary:
      "The two numbers that drive acute stroke care, why the first scan is a CT, and how mechanism determines secondary prevention.",
    audioScript: [
      "Acute stroke care is a choreographed sequence, and the entire thing is organized around two numbers you obtain in the first minutes.",
      "Number one is the last-known-well time. Not when the symptoms were noticed — when the patient was last observed at neurologic baseline. This determines reperfusion eligibility, and nothing substitutes for it. If a patient wakes with symptoms, the last known well is when they went to sleep.",
      "Number two is the bedside glucose. Hypoglycemia is the most common fully reversible stroke mimic and it takes seconds to exclude. Treating it costs nothing; missing it is unforgivable.",
      "Then imaging. The immediate study is a noncontrast head computed tomography, and the reason is specific: computed tomography is poor at showing early ischemia but excellent and fast at excluding hemorrhage. Hemorrhage absolutely contraindicates thrombolysis, so this scan exists to answer one question quickly.",
      "If the patient is within the window with no contraindication, reperfusion therapy is the single most impactful acute intervention. Thrombolysis requires blood pressure below a defined threshold, so that is one of the few situations in acute ischemic stroke where you lower blood pressure deliberately. Otherwise, blood pressure is left permissively elevated to maintain perfusion to the ischemic penumbra. Large vessel occlusion may also be eligible for mechanical thrombectomy in an extended window.",
      "Now the part that prevents the most common complication of the admission: a bedside swallow screen before anything goes in the patient's mouth, including oral medications. Aspiration pneumonia after stroke is common, morbid and preventable, and the screen takes two minutes.",
      "Finally, secondary prevention, which is determined by mechanism. A large-artery atherosclerotic or small-vessel stroke is prevented with antiplatelet therapy and a high-intensity statin. A cardioembolic stroke from atrial fibrillation is prevented with anticoagulation, started after a delay proportional to infarct size because of hemorrhagic transformation risk. Add blood pressure control, diabetes management, smoking cessation, and rehabilitation services. Determining mechanism is not an academic exercise — it changes the prescription.",
    ],
    keyPoints: [
      "Last-known-well time and bedside glucose come first.",
      "The immediate CT exists to exclude hemorrhage, not to show the infarct.",
      "Permissive hypertension is the rule, except when thrombolysis requires lowering.",
      "Swallow screen before any oral intake; mechanism determines prevention.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["NEURO.STROKE.01", "NEURO.STROKE.02", "NEURO.STROKE.03", "NEURO.STROKE.04", "NEURO.STROKE.05", "NEURO.STROKE.06"],
  },
  {
    code: "DEMO-LEC-011",
    title: "Seizure and Status Epilepticus",
    specialty: "Neurology",
    topic: "Seizure",
    lectureType: "CORE_LECTURE",
    summary:
      "The timed escalation algorithm, why benzodiazepine underdosing is the commonest error, and what to do when the patient does not wake up.",
    audioScript: [
      "Status epilepticus is defined operationally: five minutes or more of continuous seizure activity, or repeated seizures without recovery of consciousness in between. The five-minute definition exists because waiting longer makes seizures progressively harder to abort and causes neuronal injury.",
      "The algorithm is timed, not deliberative. In the first minutes: position the airway, suction, give oxygen, obtain intravenous access, and check a bedside glucose. Hypoglycemia is immediately correctable and must be excluded.",
      "First-line pharmacotherapy is a benzodiazepine, and here is the most important practical point in this talk: the most common treatment failure is underdosing. Clinicians give a timid dose, watch it not work, and conclude the seizure is refractory when in fact it was undertreated. Give an adequate weight-based dose.",
      "If seizures persist after adequate benzodiazepine dosing, load a second-line non-benzodiazepine antiseizure medication intravenously. Several agents are acceptable and the choice depends on comorbidities and availability. Do not delay this step to give a fourth benzodiazepine dose.",
      "If seizures continue beyond second-line therapy, the patient has refractory status epilepticus and needs intubation with a continuous anesthetic infusion and continuous electroencephalographic monitoring.",
      "In parallel, search for the precipitant. Medication nonadherence in a known epileptic is the most common cause and the easiest to fix. Also consider metabolic derangement, particularly hyponatremia and hypocalcemia, intoxication and withdrawal — especially alcohol — central nervous system infection, and structural lesions including hemorrhage, tumor and stroke.",
      "One more clinical pearl. If the convulsions stop but the patient does not wake up over the following twenty to thirty minutes, consider nonconvulsive status epilepticus. It is invisible without electroencephalography, and it is treatable. A prolonged postictal state is a diagnosis of exclusion, not an assumption.",
    ],
    keyPoints: [
      "Five minutes of continuous seizure defines status epilepticus.",
      "Airway, oxygen, access and glucose come before drugs.",
      "Underdosing the benzodiazepine is the most common treatment failure.",
      "Failure to wake up after convulsions stop suggests nonconvulsive status.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["NEURO.SZ.01", "NEURO.SZ.02", "NEURO.SZ.03", "NEURO.SZ.04", "NEURO.SZ.05"],
  },
  {
    code: "DEMO-LEC-012",
    title: "Delirium vs Dementia",
    specialty: "Neurology",
    topic: "Stroke",
    lectureType: "MORNING_REPORT",
    summary:
      "Separating an acute medical emergency from a chronic condition, and why the distinction changes everything you do next.",
    audioScript: [
      "Delirium and dementia are frequently confused at the bedside, and getting the distinction right changes your entire plan. One is an acute medical emergency with a cause to find; the other is a chronic condition to manage.",
      "The discriminating features are onset, course and attention. Delirium develops over hours to days, fluctuates markedly through the day, and the cardinal deficit is inattention — the patient cannot sustain focus, drifts, cannot follow a simple sequence. Dementia develops over months to years, follows a stable or slowly progressive course, and attention is relatively preserved until late. Memory is the prominent early deficit.",
      "Delirium also frequently involves altered consciousness, disturbed sleep-wake cycles, and perceptual disturbances. It comes in hyperactive and hypoactive forms, and the hypoactive form — the quiet, withdrawn, sleepy patient — is both more common and far more often missed. A quiet patient is not necessarily a comfortable one.",
      "Critically, the two coexist. Dementia is the single strongest risk factor for delirium. So a patient with known dementia who becomes acutely worse over two days has delirium superimposed on dementia, and requires the full acute workup. Do not attribute an acute change to the chronic diagnosis.",
      "When you identify delirium, look for causes systematically. Infection, particularly urinary and respiratory. Medications, especially anticholinergics, sedatives and opioids. Metabolic derangements. Hypoxia. Pain. Urinary retention and constipation. Withdrawal states. Environmental factors including sleep deprivation and sensory deprivation from missing glasses and hearing aids.",
      "Management is primarily non-pharmacologic and it works. Reorientation, restoring the day-night cycle, early mobilization, returning glasses and hearing aids, ensuring hydration, minimizing tethers and eliminating deliriogenic medications. Antipsychotics are reserved for severe agitation that threatens safety, are used at the lowest dose for the shortest time, and do not treat the underlying delirium.",
    ],
    keyPoints: [
      "Delirium: acute, fluctuating, inattention. Dementia: chronic, progressive, memory.",
      "Hypoactive delirium is more common and more often missed than hyperactive.",
      "An acute change in a patient with dementia is delirium until proven otherwise.",
      "Non-pharmacologic measures are the primary treatment; antipsychotics are a last resort.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["NEURO.COG.01", "PREV.DC.02", "ID.SEPSIS.01"],
  },
  {
    code: "DEMO-LEC-013",
    title: "Serotonin Syndrome vs Neuroleptic Malignant Syndrome",
    specialty: "Psychiatry",
    topic: "Toxicology",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Two hyperthermic toxidromes that look alike from the doorway and are separated by the reflex examination.",
    audioScript: [
      "Serotonin syndrome and neuroleptic malignant syndrome both present as a hyperthermic, rigid, autonomically unstable, altered patient. From the doorway they look identical. The examination and the medication list separate them, and the distinction matters.",
      "Start with the drug. Serotonin syndrome follows serotonergic agents — reuptake inhibitors, monoamine oxidase inhibitors, tramadol, triptans, certain antiemetics, and the one people forget, linezolid, which has monoamine oxidase inhibitor activity. Neuroleptic malignant syndrome follows dopamine antagonists, typically antipsychotics, or abrupt withdrawal of a dopaminergic agent.",
      "Now onset. Serotonin syndrome develops fast — usually within twenty-four hours of the offending change, often within hours. Neuroleptic malignant syndrome develops slowly, over days to weeks.",
      "The examination is where you make the call. Serotonin syndrome produces neuromuscular hyperactivity: hyperreflexia, tremor, myoclonus, and clonus that is markedly more pronounced in the lower extremities than the upper. Sustained ankle clonus in the right drug context is close to diagnostic. Neuroleptic malignant syndrome produces lead-pipe rigidity that is generalized, with normal or diminished reflexes, and bradyreflexia rather than clonus.",
      "Both cause hyperthermia, autonomic instability and elevated creatine kinase, so those features do not help you discriminate. Neuroleptic malignant syndrome tends to produce a higher creatine kinase and more severe rigidity.",
      "Treatment shares a foundation: stop the offending agent, provide aggressive supportive care, cool the patient, give fluids to protect the kidneys from rhabdomyolysis, and use benzodiazepines to control muscular hyperactivity — because the muscular activity is what generates the heat. Severe cases require paralysis and intubation. Specific antidotal therapies exist for each, but the supportive care is what saves the patient.",
      "The practical error to avoid: reaching for an antipsychotic to sedate an agitated patient who actually has serotonin syndrome. Dopamine antagonism can worsen the picture. Benzodiazepines are the safe sedative here.",
    ],
    keyPoints: [
      "Drug class and onset speed narrow it before you touch the patient.",
      "Lower-extremity predominant clonus with hyperreflexia is serotonin toxicity.",
      "Generalized lead-pipe rigidity with hyporeflexia is neuroleptic malignant syndrome.",
      "Benzodiazepines, not antipsychotics, are the sedative of choice in serotonin syndrome.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PSYCH.SS.01", "PSYCH.SS.02", "PSYCH.SS.03", "PSYCH.SS.04", "PSYCH.SS.05"],
  },
  {
    code: "DEMO-LEC-014",
    title: "Alcohol Withdrawal",
    specialty: "Psychiatry",
    topic: "Substance Use",
    lectureType: "CORE_LECTURE",
    summary:
      "The withdrawal timeline, symptom-triggered benzodiazepine dosing, and the thiamine rule.",
    audioScript: [
      "Alcohol withdrawal follows a predictable timeline, and knowing it lets you anticipate rather than react.",
      "Six to twelve hours after the last drink: tremor, anxiety, sweating, nausea, mild autonomic hyperactivity. Twelve to twenty-four hours: alcoholic hallucinosis, where patients experience hallucinations but retain a clear sensorium. Twelve to forty-eight hours: withdrawal seizures, typically generalized tonic-clonic. Forty-eight to ninety-six hours: delirium tremens — confusion, disorientation, hallucinations, severe autonomic hyperactivity and fever. That last one carries real mortality even when treated.",
      "First-line treatment is benzodiazepines, because they are cross-tolerant with alcohol at the same receptor. They are the only agents shown to prevent withdrawal seizures and delirium. Symptom-triggered dosing guided by a standardized withdrawal scale, with frequent structured reassessment, uses less total medication and shortens treatment duration compared with fixed schedules — as long as the reassessment actually happens.",
      "Beta blockers are a trap. They control the tachycardia, which makes the patient look better and removes the sign your scale depends on, without preventing seizures or delirium. Antipsychotics lower the seizure threshold and should not be used as monotherapy.",
      "Now the thiamine rule, which is simple and frequently violated. Chronic alcohol use depletes thiamine. Thiamine is a cofactor for glucose metabolism. Give a glucose load to a thiamine-deficient patient and you can precipitate Wernicke encephalopathy. So: thiamine before or with any glucose-containing fluid. Give it empirically — do not wait for a level. Replete magnesium and potassium as well, because both are commonly depleted and both lower the seizure threshold.",
      "Risk-stratify. A history of prior withdrawal seizures or delirium tremens is the strongest predictor that it will happen again, and it raises the monitoring intensity you need.",
      "Finally, treating the withdrawal is not treating the disorder. Before discharge, offer relapse prevention pharmacotherapy, make a treatment referral, continue vitamin supplementation, and arrange follow-up. A patient who survives withdrawal and leaves with nothing else will be back.",
    ],
    keyPoints: [
      "Know the timeline: tremor early, seizures at 12 to 48 hours, delirium tremens at 48 to 96.",
      "Symptom-triggered benzodiazepines with structured reassessment are first-line.",
      "Thiamine before or with any glucose — empirically, never waiting for a level.",
      "Prior withdrawal seizure is the strongest predictor of severe withdrawal.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PSYCH.ETOH.01", "PSYCH.ETOH.02", "PSYCH.ETOH.03", "PSYCH.ETOH.04"],
  },
  {
    code: "DEMO-LEC-015",
    title: "Pediatric Dehydration",
    specialty: "Pediatrics",
    topic: "Gastroenterology",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Grading dehydration clinically, why oral rehydration is first-line, and what caregivers need to hear before they go home.",
    audioScript: [
      "Dehydration in children is graded clinically. The laboratory adds very little, and waiting for it delays treatment.",
      "The findings you are assessing are capillary refill, mucous membranes, presence of tears, skin turgor, urine output, heart rate, and — most importantly — the child's activity level and interactiveness. A child who is alert, interactive and consolable is not in shock, whatever the numbers say.",
      "Roughly: mild dehydration has minimal findings. Moderate dehydration has dry mucous membranes, decreased tears, delayed capillary refill and reduced urine output, but the child remains alert with a normal blood pressure. Severe dehydration adds lethargy, markedly delayed capillary refill, mottling, tachycardia, and eventually hypotension — which in a child is a late and ominous sign, because children compensate well right up until they do not.",
      "Oral rehydration therapy is first-line for mild and moderate dehydration and it is genuinely as effective as intravenous fluid, with fewer complications and no need for a needle in a small child. The technique is what makes it work: small frequent volumes, given by syringe or spoon, every few minutes. Large volumes provoke vomiting.",
      "If vomiting is limiting intake, a single weight-based dose of an antiemetic substantially improves the success rate of oral rehydration and reduces the need for intravenous therapy and hospitalization.",
      "Intravenous isotonic fluid is reserved for severe dehydration or shock, altered mental status, intractable vomiting despite an antiemetic, or documented failure of an adequate oral rehydration trial. Age alone is not an indication.",
      "Antibiotics are not indicated in routine viral gastroenteritis, which is what most of these children have. Watery non-bloody diarrhea with sick contacts is viral, and antibiotics add adverse effects without benefit.",
      "The discharge conversation is the safety net and deserves as much attention as the treatment. Teach the caregiver how to give oral rehydration solution at home. Resume a normal age-appropriate diet — prolonged food restriction and clear-liquid-only regimens cause harm. And give explicit return precautions: decreased urine output, lethargy, inability to keep fluids down, blood in the stool, or a worsening appearance.",
    ],
    keyPoints: [
      "Grade dehydration clinically; the child's activity level matters most.",
      "Oral rehydration in small frequent volumes is first-line for mild to moderate.",
      "An antiemetic dose improves oral rehydration success and reduces admissions.",
      "Resume normal diet and give explicit, concrete return precautions.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PEDS.DEHY.01", "PEDS.DEHY.02", "PEDS.DEHY.03", "PEDS.DEHY.04", "PEDS.DEHY.05"],
  },
  {
    code: "DEMO-LEC-016",
    title: "Pediatric Respiratory Distress",
    specialty: "Pediatrics",
    topic: "Pulmonology",
    lectureType: "CORE_LECTURE",
    summary:
      "Assessing work of breathing in a child, treating the exacerbation, and recognizing the quiet child who is about to fail.",
    audioScript: [
      "Assessing a child in respiratory distress is a skill you develop by looking, and the most useful information is available before you touch them.",
      "Watch the work of breathing. Nasal flaring, head bobbing, grunting, retractions — subcostal, intercostal, supraclavicular — and accessory muscle use. Listen to how they speak or cry: full sentences, short phrases, single words, or not at all. Note the position they have chosen. And assess mental status, because agitation followed by drowsiness is the trajectory toward failure.",
      "Then localize. Stridor is upper airway. Wheeze is lower airway obstruction. Crackles suggest alveolar disease. Grunting suggests loss of lung volume. A quiet chest with visible effort is the most dangerous finding of all, because it means air is not moving.",
      "For an asthma exacerbation, the acute treatment is repeated inhaled short-acting bronchodilator — given back-to-back in moderate to severe presentations — plus early systemic corticosteroid, plus oxygen for hypoxemia. Early steroids reduce hospitalization and relapse, and the route matters less than the timing.",
      "For severe exacerbations not responding to that, intravenous magnesium is a reasonable adjunct. It supplements rather than replaces the core therapy.",
      "Warning signs that a child is decompensating: inability to speak in phrases, a silent chest, drowsiness or profound agitation, cyanosis, and a carbon dioxide that is normal or rising in a tachypneic child. That last one is subtle and important — a normalizing carbon dioxide in an obstructed, tachypneic child means fatigue, not improvement.",
      "One thing never to do: sedate a child in respiratory distress. The anxiety is hypoxia and air hunger. Sedation removes the respiratory drive that is keeping them alive.",
      "Before discharge, ask what will be different at home. A child with repeated visits on rescue inhaler alone has inadequately controlled asthma. They need controller therapy, a spacer, technique taught and observed rather than assumed, a written action plan, trigger review and follow-up. Without those, you will see them again.",
    ],
    keyPoints: [
      "Assess work of breathing, speech, position and mental status before touching the child.",
      "Repeated bronchodilators plus early systemic steroids are the core of exacerbation care.",
      "A silent chest and a rising carbon dioxide are pre-arrest findings.",
      "Never sedate a child in respiratory distress.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PEDS.ASTHMA.01", "PEDS.ASTHMA.02", "PEDS.ASTHMA.03", "PEDS.ASTHMA.04", "PEDS.ASTHMA.05"],
  },
  {
    code: "DEMO-LEC-017",
    title: "Hypertensive Disorders of Pregnancy",
    specialty: "OB/GYN",
    topic: "Obstetrics",
    lectureType: "CORE_LECTURE",
    summary:
      "The spectrum from gestational hypertension to eclampsia, and the two-drug rule for severe features.",
    audioScript: [
      "The hypertensive disorders of pregnancy form a spectrum, and knowing where a patient sits on it determines what you do in the next hour.",
      "Chronic hypertension predates pregnancy or appears before twenty weeks. Gestational hypertension is new hypertension after twenty weeks without proteinuria or severe features. Preeclampsia adds proteinuria or, importantly, severe features even without proteinuria. Eclampsia is preeclampsia with seizures.",
      "The severe features are the ones to memorize, because their presence changes management immediately. Systolic blood pressure at or above one hundred sixty, or diastolic at or above one hundred ten, confirmed on repeat. New neurologic symptoms — headache unresponsive to medication, visual disturbances. Right upper quadrant or epigastric pain. Elevated liver transaminases. Thrombocytopenia. Pulmonary edema. New renal insufficiency.",
      "Here is the rule that matters most, and the one most often confused. Severe features require two separate drugs for two separate problems. Magnesium sulfate for seizure prophylaxis. And a fast-acting intravenous antihypertensive — labetalol or hydralazine — for the severe-range blood pressure. Magnesium is not an antihypertensive. Giving magnesium and considering the blood pressure treated is a serious error, because maternal intracranial hemorrhage is what severe-range hypertension causes.",
      "While magnesium is infusing, monitor for toxicity clinically: deep tendon reflexes and respiratory rate, with levels as a supplement. Loss of reflexes is the earliest sign. Calcium gluconate is the antidote and should be immediately available.",
      "Definitive treatment is delivery. Timing balances gestational age against maternal and fetal risk, and with severe features at or beyond thirty-four weeks, delivery is generally indicated. Corticosteroids for fetal lung maturity are given at earlier gestational ages. Continuous fetal monitoring runs throughout, because there are two patients.",
      "Do not forget the postpartum period. Preeclampsia and eclampsia can present or worsen after delivery, sometimes days later. Early blood pressure follow-up and explicit warning signs given to the patient are essential, along with counseling about future pregnancy risk and long-term cardiovascular risk.",
    ],
    keyPoints: [
      "Severe features change management even without proteinuria.",
      "Magnesium prevents seizures; a separate fast-acting agent treats the blood pressure.",
      "Monitor magnesium toxicity by reflexes and respiratory rate; calcium gluconate is the antidote.",
      "Delivery is definitive, and preeclampsia can still present postpartum.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["OB.PREE.01", "OB.PREE.02", "OB.PREE.03", "OB.PREE.04", "OB.PREE.05"],
  },
  {
    code: "DEMO-LEC-018",
    title: "Early Pregnancy Emergencies",
    specialty: "OB/GYN",
    topic: "Early Pregnancy",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Why the pregnancy test comes first, how ultrasound and beta-hCG are read together, and the stability branch point in ectopic pregnancy.",
    audioScript: [
      "There is one rule that prevents most early pregnancy disasters: in any woman of reproductive age with abdominal or pelvic pain, the pregnancy test comes first. Before imaging, before analgesia decisions, before the differential.",
      "With a positive test and pain or bleeding, you are working through three possibilities: a normal intrauterine pregnancy, a failing intrauterine pregnancy, and an ectopic pregnancy. Ectopic pregnancy is the one that kills, so it is the one you must exclude.",
      "The workup pairs two tests that must be read together. Transvaginal ultrasound is the imaging study of choice. Quantitative beta-hCG gives you a number to interpret it against. Above the discriminatory zone, an intrauterine gestational sac should be visible; if it is not, and particularly if there is an adnexal mass or free pelvic fluid, you are dealing with an ectopic pregnancy until proven otherwise. Below the discriminatory zone, an indeterminate ultrasound requires serial beta-hCG measurements, because a normal early pregnancy shows a characteristic rise.",
      "Once you suspect ectopic pregnancy, the immediate branch point is hemodynamic stability. An unstable patient — hypotensive, tachycardic, poorly perfused, with a falling hemoglobin — has likely ruptured and goes to the operating room. That is not a discussion, it is a resuscitation with surgical control of bleeding.",
      "The stable patient with an unruptured ectopic has a real choice between methotrexate and laparoscopic surgery. Methotrexate requires several things simultaneously: hemodynamic stability, an unruptured mass within acceptable size limits, a beta-hCG below a threshold, normal hepatic renal and hematologic function, no contraindications, and — this is as much a criterion as any laboratory value — a patient who can reliably return for serial monitoring. The treatment depends on follow-up.",
      "Two practical points. Determine Rh status: an Rh-negative woman with early pregnancy bleeding needs Rh immune globulin. And after methotrexate, the treatment is not complete until the beta-hCG is undetectable. She can still rupture during that period, so explicit rupture warning signs and a monitoring schedule are part of the discharge.",
    ],
    keyPoints: [
      "Pregnancy test first in any reproductive-age woman with pelvic pain.",
      "Read beta-hCG and transvaginal ultrasound together against the discriminatory zone.",
      "Instability means the operating room; stability opens the medical-versus-surgical choice.",
      "Methotrexate requires reliable follow-up and serial beta-hCG to undetectable.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["OB.ECTOPIC.01", "OB.ECTOPIC.02", "OB.ECTOPIC.03", "OB.ECTOPIC.04"],
  },
  {
    code: "DEMO-LEC-019",
    title: "Acute Surgical Abdomen",
    specialty: "Surgery",
    topic: "Acute Abdomen",
    lectureType: "GRAND_ROUNDS",
    summary:
      "Recognizing the abdomen that needs an operation, choosing imaging by location and population, and the preoperative bundle.",
    audioScript: [
      "The question in an acute abdomen is not primarily what the diagnosis is. It is whether this patient needs an operation, and how urgently. Everything else follows from that.",
      "The findings that suggest a surgical abdomen: pain that is constant and progressive rather than colicky and resolving, localized or diffuse peritoneal signs, a patient who lies very still because movement hurts, systemic signs of inflammation, and the absence of an obvious medical explanation. Peritonitis with hemodynamic instability is a surgical emergency and imaging must not delay the operating room.",
      "Location narrows the differential efficiently. Right lower quadrant: appendicitis, and in the right patient ovarian or tubal pathology. Right upper quadrant: biliary disease. Left lower quadrant: diverticulitis. Epigastric: pancreatitis, peptic ulcer, and remember that inferior myocardial infarction can present as epigastric pain. Diffuse: obstruction, perforation, mesenteric ischemia.",
      "The history often makes the diagnosis before imaging. Appendicitis classically begins as vague periumbilical pain that migrates to the right lower quadrant and becomes sharp, with anorexia preceding the vomiting. Biliary colic is postprandial right upper quadrant pain resolving over a few hours; when it persists beyond several hours with fever and leukocytosis, it has become cholecystitis.",
      "Imaging choice follows location and population. Right upper quadrant ultrasound for biliary disease — no radiation, sensitive for stones, and it visualizes the duct. Computed tomography of the abdomen and pelvis for most adult acute abdomens. Ultrasound first in children and in pregnancy to avoid radiation.",
      "The preoperative bundle is the same regardless of diagnosis: nothing by mouth, intravenous fluids, analgesia, antiemetics, appropriate antibiotics, and early surgical consultation. On analgesia specifically — the old teaching that opioids obscure the examination is outdated and has been repeatedly refuted. Withholding pain medication does not improve diagnostic accuracy; it just causes suffering.",
      "One last point on timing. Delay in appendicitis leads to perforation, and delay in cholecystitis leads to gangrene and perforation. Early surgical involvement is not a courtesy — it shortens the time to definitive treatment and reduces complications.",
    ],
    keyPoints: [
      "The question is whether an operation is needed, and how urgently.",
      "Location plus the character and evolution of pain narrows the differential.",
      "Ultrasound for biliary disease, children and pregnancy; CT for most adults.",
      "Analgesia does not obscure the examination — withholding it is outdated.",
    ],
    estimatedMinutes: 6,
    conceptCodes: ["SURG.APPY.01", "SURG.APPY.02", "SURG.APPY.03", "SURG.CHOLE.01", "SURG.CHOLE.02", "SURG.CHOLE.03"],
  },
  {
    code: "DEMO-LEC-020",
    title: "Preventive Care, Discharge Planning, and Follow-Up",
    specialty: "Preventive Care",
    topic: "Preventive Care",
    lectureType: "NOON_CONFERENCE",
    summary:
      "Treating discharge as a clinical intervention with its own failure modes, and using the admission to close preventive gaps.",
    audioScript: [
      "Discharge is a clinical intervention with its own failure modes, and it deserves the same rigor as any procedure you perform. The transition out of the hospital is where a substantial fraction of preventable harm occurs.",
      "Start with medication reconciliation, done explicitly rather than assumed. Compare the pre-admission list against the discharge list, item by item. What was stopped, and does the patient know why? What was started, and does the patient know what it is for? What was changed in dose? What was held during the admission and needs to be resumed — or deliberately not resumed?",
      "Then ask the question that predicts readmission better than almost anything else: can this patient actually obtain and take these medications? Cost, transportation, literacy, dexterity, vision, and whether someone at home can help. A perfect prescription the patient cannot fill is not a treatment plan. Many readmissions trace back to exactly this, and it is discoverable in one conversation.",
      "Every discharge needs three explicit elements. First, follow-up with a named clinician and a defined timeframe — ideally scheduled before the patient leaves rather than left as an instruction. Second, return precautions in concrete language: not 'return if you feel worse,' but the specific symptoms that should bring them back. Third, a clear statement of what was found and what was done, in language the patient can repeat back.",
      "Use the admission to close preventive gaps, because hospitalized patients are a captive population with identified needs. Vaccination status — pneumococcal, influenza and others as indicated. Cancer screening appropriate to age. Smoking cessation counseling with pharmacotherapy offered, not just advice. Substance use screening. Depression screening. Blood pressure, lipid and diabetes management.",
      "Finally, ask the question that should end every discharge planning conversation: why was this patient admitted, and what has changed so that it will not happen again? If the answer is nothing — if the medication they could not afford is unchanged, the inhaler technique is untaught, the follow-up unscheduled — then the admission treated the episode and left the cause intact.",
    ],
    keyPoints: [
      "Reconcile medications explicitly, item by item, against the pre-admission list.",
      "Ask whether the patient can actually obtain and take the regimen.",
      "Named follow-up, concrete return precautions, and a plan the patient can repeat back.",
      "Close preventive gaps and ask what changed so this admission does not repeat.",
    ],
    estimatedMinutes: 5,
    conceptCodes: ["PREV.DC.01", "PREV.DC.02", "PREV.SCREEN.01", "PULM.CAP.05"],
  },
];
